- name: Demo on Variables
  hosts: all
  vars:
    URL1: play.google.com
    #PlayLevel variables
  tasks: 
    - name: Print a Variable
      debug: 
        msg: URL = {{URL}}
    - name: Print a Variable from file
      debug: 
        msg: URL={{URL2}}
        