- name: Demo on tasks Tags
  hosts: all
  tasks:
    - name: CentOS
      debug:
        msg: CentOS
      tags: 
        - centos

    - name: Ubuntu
      debug:  
        msg: Ubuntu
      tags:
        - ubuntu